### ISSUE TITLE
NA Predictions with Nodes Provided

### ISSUE THREAD

**Issue by NathanHebertMSVU** [lawlerem/starve#13]
It seems that providing node locations to strv_prepare might result in NA predictions down the line (even for training data).

**Reproducible example code:**
_data(bird_survey)
bird_model<- strv_prepare(
    cnt ~ time(year),
    data = bird_survey, nodes = bird_survey[1:100,],
    distribution = "poisson"
)
bird_model<- strv_fit(
    bird_model,
    silent = TRUE
)
sf_pred<- strv_predict(
    bird_model,
    bird_survey
)
sf_pred_

**Comment by lawlerem** [comment]
Can you elaborate on what the problem is? What is the expected output and what is different in the actual output?

**Comment by NathanHebertMSVU** [comment]
![Capture](https://user-images.githubusercontent.com/62037477/189981534-5fafb881-c7bf-49a4-a911-d64740af3e73.png)

I apologize for being rather vague. I guess I'm wondering why you get NA's if you run the code given above.
