### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by shahriar49** [lawlerem/staRVe#17]
Hi,
I have R4.4.0 and rtools44 installed on my Windows (fresh installation). But when I run the installation command:
 
`devtools::install_github("lawlerem/starve", build_vignettes = TRUE)`

it fails to install. First of all, it fails to update Rcpp (although it is installed in my user directory). But even when I select not to update it, install still fails. below is the installation log:

```
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────
   checking for file 'C:\Users\sheydari\AppData\Local\Temp\RtmpqSCpFN\remotes3c8039477649\lawlerem-starve-5dcdc3c/DESCRI✔  checking for file 'C:\Users\sheydari\AppData\Local\Temp\RtmpqSCpFN\remotes3c8039477649\lawlerem-starve-5dcdc3c/DESCRIPTION' (468ms)
─  preparing 'starve': (383ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes (15.2s)
         -----------------------------------
─  installing *source* package 'starve' ...
   ** using staged installation
   ** libs
         0 [main] make (7928) C:\rtools44\usr\bin\make.exe: *** fatal error - add_item ("\??\C:\rtools44", "/", ...) failed, errno 1
   Stack trace:
   Frame         Function      Args
   0007FFFFABC0  00018005FEBE (000180287E5A, 000180269B81, 000000008000, 0007FFFF8B30) msys-2.0.dll+0x1FEBE
   0007FFFFABC0  0001800467F9 (0007FFFFABDE, 0007FFFFABC0, 000000000000, 000000000000) msys-2.0.dll+0x67F9
   0007FFFFABC0  000180046832 (0007FFFF9BC0, 000000000001, 000000008000, 000000000001) msys-2.0.dll+0x6832
   0007FFFFABC0  00018007CE0A (000700000000, 000000000000, 0007FFFFCC18, 000000000000) msys-2.0.dll+0x3CE0A
   1DB14598AC0874B  00018017E0D5 (000000000000, 000000000000, 000000000170, 000000000000) msys-2.0.dll+0x13E0D5
   0007FFFFCD30  000180046E60 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x6E60
   000000000000  000180045AC3 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5AC3
   0007FFFFFFF0  000180045B74 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5B74
   End of stack trace
   Loaded modules:
   000100400000 make.exe
   7FFB99A10000 ntdll.dll
   7FFB98450000 KERNEL32.DLL
   7FFB96E90000 KERNELBASE.dll
   000430B30000 msys-intl-8.dll
   000180040000 msys-2.0.dll
   0005603F0000 msys-iconv-2.dll
   7FFB98380000 advapi32.dll
   7FFB97740000 msvcrt.dll
   7FFB99640000 sechost.dll
   7FFB97710000 bcrypt.dll
   7FFB998B0000 RPCRT4.dll
   7FFB965B0000 CRYPTBASE.DLL
   7FFB96E10000 bcryptPrimitives.dll
   Warning in system(paste(MAKE, p1(paste("-f", shQuote(makefiles))), "compilers"),  :
     running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-44~1.0/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-44~1.0/share/make/winshlib.mk" -f "C:\Users\sheydari\AppData\Local\Temp\RtmpqSCpFN\file3c80768531d2" compilers' had status 256
   Error in if (nzchar(cxx)) { : argument is of length zero
─  removing 'C:/Users/sheydari/AppData/Local/Temp/Rtmp2T0gH1/Rinst7e6c62827322/starve'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'starve' from GitHub:
  ! System command 'Rcmd.exe' failed
```

Could you please help me to solve this problem?

**Comment by lawlerem** [comment]
I'm afraid I'm not going to be much help on compiling on Windows but I can try...

Are you able to install other packages from source?

**Comment by shahriar49** [comment]
Thanks for reply. Actually I was able to install it finally under R4.4.1 and Rtools 44 (I am using Windows 11). Also, I could not install it under R console but it was possible under R-studio. The problem seems to be that the R-studio includes a pandoc installation by default but R console does not, and pandoc is needed to install vignettes (it was not mentioned in the installation readme). I got a lot of warnings and messages that I do not understand, but it did not prohibit me from loading the starve package.
I also found some differences between the code specified in the paper (https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.14053) and the code drafted in the starve-tour.rmd file. For example, the paper says that the model is fitted by running: 

bird_fit <- strv_prepare(
    cnt ~ time(year),
    bird_survey,
    distribution = "poisson",
    fit = TRUE
)

However, running this code will lead to false convergence and I had to modify the second line to be cnt ~ time(year, "rw") to get a relative convergence response.

**Comment by lawlerem** [comment]
I'm glad you got it running. I have made some modifications to the code and default settings since the publication of the package. If you want to install to the version of the code that was available when the article was published you can install the "publication" release (it should be in a section on the right-hand side of the main page of this repository).

**Comment by shahriar49** [comment]
Hi Ethan,
Thanks for your reply. I will just continue with the current version and R
markdown file and that is fine.
May I ask another question? I have a dataset containing the estimated
biomass production at different locations throughout the country. The data
is presented for the crop growing days (spring till fall) for each year for
each location. I also have another dataset containing a drought index for
the same locations for the same years and days. And I want to see how they
are correlated. So I think of your package to build a spatio-temporal
model, having crop biomass as the response and the drought index as
covariate. But I am not sure how to make my data cubes. In your bird survey
example, your response variable was the observed counts per point per
year, so the time step was year. Here I have the time step as days, but for
each point I have multiple years of data. Should I consider the year as
another covariate and have the day being the temporal variable of the model?
Looking for your help.

P.S. Sorry if it is not the right place to ask this question. I did not have any other email from you to use.

Best Regards
Shahriar
